# -*- coding: utf-8 -*-
"""Q1module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13eFrNpr5kPdgDcOULzsOel3o32JcmNf_
"""

a = 0
def b():
 global a
 a = c(a)
def c(a):
 return a + 2